
$(document).ready(function(){
$(".sub-div-inst").hide();
$(".sub-div-tt").hide();
$(".sub-div-cont").hide();
$(".sub-div-bio").hide();
$(".sub-div-rec").hide();
$(".sub-div-cnslt").hide();
$(".sub-div-under").hide();
$(".sub-div-leave").hide();
$(".divinst").click(function(){
$(".sub-div-leave").hide();
$(".sub-div-tt").hide();
$(".sub-div-cont").hide();
$(".sub-div-bio").hide();
$(".sub-div-rec").hide();
$(".sub-div-cnslt").hide();
$(".sub-div-under").hide();
$(".sub-div-inst").toggle();
});
});
$(document).ready(function(){
$(".sub-div-inst").hide();
$(".sub-div-tt").hide();
$(".sub-div-cont").hide();
$(".sub-div-bio").hide();
$(".sub-div-rec").hide();
$(".sub-div-cnslt").hide();
$(".sub-div-under").hide();
$(".sub-div-leave").hide();
$(".div-tt").click(function(){
$(".sub-div-leave").hide();
$(".sub-div-tt").toggle();
$(".sub-div-cont").hide();
$(".sub-div-bio").hide();
$(".sub-div-rec").hide();
$(".sub-div-cnslt").hide();
$(".sub-div-under").hide();
$(".sub-div-inst").hide();
});
});
$(document).ready(function(){
$(".sub-div-inst").hide();
$(".sub-div-tt").hide();
$(".sub-div-cont").hide();
$(".sub-div-bio").hide();
$(".sub-div-rec").hide();
$(".sub-div-cnslt").hide();
$(".sub-div-under").hide();
$(".sub-div-leave").hide();
$(".div-cont").click(function(){
$(".sub-div-leave").hide();
$(".sub-div-tt").hide();
$(".sub-div-cont").toggle();
$(".sub-div-bio").hide();
$(".sub-div-rec").hide();
$(".sub-div-cnslt").hide();
$(".sub-div-under").hide();
$(".sub-div-inst").hide();
});
});
$(document).ready(function(){
$(".sub-div-inst").hide();
$(".sub-div-tt").hide();
$(".sub-div-cont").hide();
$(".sub-div-bio").hide();
$(".sub-div-rec").hide();
$(".sub-div-cnslt").hide();
$(".sub-div-under").hide();
$(".sub-div-leave").hide();
$(".div-bio").click(function(){
$(".sub-div-leave").hide();
$(".sub-div-tt").hide();
$(".sub-div-cont").hide();
$(".sub-div-bio").toggle();
$(".sub-div-rec").hide();
$(".sub-div-cnslt").hide();
$(".sub-div-under").hide();
$(".sub-div-inst").hide();
});
});
$(document).ready(function(){
$(".sub-div-inst").hide();
$(".sub-div-tt").hide();
$(".sub-div-cont").hide();
$(".sub-div-bio").hide();
$(".sub-div-rec").hide();
$(".sub-div-cnslt").hide();
$(".sub-div-under").hide();
$(".sub-div-leave").hide();
$(".div-rec").click(function(){
$(".sub-div-leave").hide();
$(".sub-div-tt").hide();
$(".sub-div-cont").hide();
$(".sub-div-bio").hide();
$(".sub-div-rec").toggle();
$(".sub-div-cnslt").hide();
$(".sub-div-under").hide();
$(".sub-div-inst").hide();
});
});
$(document).ready(function(){
$(".sub-div-inst").hide();
$(".sub-div-tt").hide();
$(".sub-div-cont").hide();
$(".sub-div-bio").hide();
$(".sub-div-rec").hide();
$(".sub-div-cnslt").hide();
$(".sub-div-under").hide();
$(".sub-div-leave").hide();
$(".div-cnslt").click(function(){
$(".sub-div-leave").hide();
$(".sub-div-tt").hide();
$(".sub-div-cont").hide();
$(".sub-div-bio").hide();
$(".sub-div-rec").hide();
$(".sub-div-cnslt").toggle();
$(".sub-div-under").hide();
$(".sub-div-inst").hide();
});
});
$(document).ready(function(){
$(".sub-div-inst").hide();
$(".sub-div-tt").hide();
$(".sub-div-cont").hide();
$(".sub-div-bio").hide();
$(".sub-div-rec").hide();
$(".sub-div-cnslt").hide();
$(".sub-div-under").hide();
$(".sub-div-leave").hide();
$(".div-undr").click(function(){
$(".sub-div-leave").hide();
$(".sub-div-tt").hide();
$(".sub-div-cont").hide();
$(".sub-div-bio").hide();
$(".sub-div-rec").hide();
$(".sub-div-cnslt").hide();
$(".sub-div-under").toggle();
$(".sub-div-inst").hide();
});
});
$(document).ready(function(){
$(".sub-div-inst").hide();
$(".sub-div-tt").hide();
$(".sub-div-cont").hide();
$(".sub-div-bio").hide();
$(".sub-div-rec").hide();
$(".sub-div-cnslt").hide();
$(".sub-div-under").hide();
$(".sub-div-leave").hide();
$(".div-leave").click(function(){
$(".sub-div-leave").toggle();
$(".sub-div-tt").hide();
$(".sub-div-cont").hide();
$(".sub-div-bio").hide();
$(".sub-div-rec").hide();
$(".sub-div-cnslt").hide();
$(".sub-div-under").hide();
$(".sub-div-inst").hide();
});
});
$(document).ready(function(){
	$(".sub-div-header").hide();
	$(".header-div").click(function(){
	$(".sub-div-header").toggle();
});
});	